/**
 * Mock data store for the Admin dashboard.
 * All data lives here and is ready to be swapped out for real API calls.
 * Replace each function body with a FastAPI call when the DB is ready.
 */
import type {
  Profile,
  Project,
  Task,
  ActivityLog,
  WorkflowRisk,
  Repository,
  ProjectStatus,
  TaskStatus,
  TaskPriority,
  RiskSeverity,
  RiskStatus,
} from "../types";

// ---------------------------------------------------------------------------
// Profiles / Users  (20 realistic records)
// ---------------------------------------------------------------------------
export const MOCK_USERS: Profile[] = [
  { id: "u1",  full_name: "Alice Johnson",    email: "alice@devflow.io",    role: "ADMIN",       is_active: true,  created_at: "2026-01-10T08:00:00Z", updated_at: "2026-09-01T10:00:00Z" },
  { id: "u2",  full_name: "Bob Martinez",     email: "bob@devflow.io",      role: "MANAGER",     is_active: true,  created_at: "2026-01-15T09:00:00Z", updated_at: "2026-08-20T12:00:00Z" },
  { id: "u3",  full_name: "Carol Williams",   email: "carol@devflow.io",    role: "DEVELOPER",   is_active: true,  created_at: "2026-02-01T10:00:00Z", updated_at: "2026-09-10T08:30:00Z" },
  { id: "u4",  full_name: "David Chen",       email: "david@devflow.io",    role: "DEVELOPER",   is_active: true,  created_at: "2026-02-05T11:00:00Z", updated_at: "2026-09-05T15:00:00Z" },
  { id: "u5",  full_name: "Eva Patel",        email: "eva@devflow.io",      role: "TEAM_MEMBER", is_active: true,  created_at: "2026-02-10T08:30:00Z", updated_at: "2026-09-12T09:00:00Z" },
  { id: "u6",  full_name: "Frank Nguyen",     email: "frank@devflow.io",    role: "DEVELOPER",   is_active: true,  created_at: "2026-02-15T09:00:00Z", updated_at: "2026-09-15T11:00:00Z" },
  { id: "u7",  full_name: "Grace Kim",        email: "grace@devflow.io",    role: "MANAGER",     is_active: true,  created_at: "2026-03-01T10:00:00Z", updated_at: "2026-09-18T14:00:00Z" },
  { id: "u8",  full_name: "Henry Thompson",   email: "henry@devflow.io",    role: "DEVELOPER",   is_active: false, created_at: "2026-03-10T11:00:00Z", updated_at: "2026-08-30T16:00:00Z" },
  { id: "u9",  full_name: "Iris Singh",       email: "iris@devflow.io",     role: "TEAM_MEMBER", is_active: true,  created_at: "2026-03-15T08:00:00Z", updated_at: "2026-09-20T10:00:00Z" },
  { id: "u10", full_name: "James OBrien",     email: "james@devflow.io",    role: "DEVELOPER",   is_active: true,  created_at: "2026-03-20T09:00:00Z", updated_at: "2026-09-22T12:00:00Z" },
  { id: "u11", full_name: "Karen Lee",        email: "karen@devflow.io",    role: "TEAM_MEMBER", is_active: true,  created_at: "2026-04-01T10:00:00Z", updated_at: "2026-09-25T08:00:00Z" },
  { id: "u12", full_name: "Leo Ramirez",      email: "leo@devflow.io",      role: "DEVELOPER",   is_active: false, created_at: "2026-04-05T11:00:00Z", updated_at: "2026-09-01T09:00:00Z" },
  { id: "u13", full_name: "Mia Robinson",     email: "mia@devflow.io",      role: "TEAM_MEMBER", is_active: true,  created_at: "2026-04-10T08:30:00Z", updated_at: "2026-09-26T10:00:00Z" },
  { id: "u14", full_name: "Nathan Brooks",    email: "nathan@devflow.io",   role: "MANAGER",     is_active: true,  created_at: "2026-04-15T09:00:00Z", updated_at: "2026-09-27T11:00:00Z" },
  { id: "u15", full_name: "Olivia Torres",    email: "olivia@devflow.io",   role: "DEVELOPER",   is_active: true,  created_at: "2026-05-01T10:00:00Z", updated_at: "2026-09-28T08:00:00Z" },
  { id: "u16", full_name: "Paul Anderson",    email: "paul@devflow.io",     role: "DEVELOPER",   is_active: true,  created_at: "2026-05-10T11:00:00Z", updated_at: "2026-09-28T09:00:00Z" },
  { id: "u17", full_name: "Quinn Jackson",    email: "quinn@devflow.io",    role: "TEAM_MEMBER", is_active: false, created_at: "2026-05-15T08:00:00Z", updated_at: "2026-08-15T12:00:00Z" },
  { id: "u18", full_name: "Rachel Scott",     email: "rachel@devflow.io",   role: "DEVELOPER",   is_active: true,  created_at: "2026-06-01T09:00:00Z", updated_at: "2026-09-27T14:00:00Z" },
  { id: "u19", full_name: "Sam Wright",       email: "sam@devflow.io",      role: "TEAM_MEMBER", is_active: true,  created_at: "2026-06-15T10:00:00Z", updated_at: "2026-09-26T15:00:00Z" },
  { id: "u20", full_name: "Tina Hernandez",   email: "tina@devflow.io",     role: "TEAM_MEMBER", is_active: true,  created_at: "2026-07-01T11:00:00Z", updated_at: "2026-09-28T10:00:00Z" },
];

// ---------------------------------------------------------------------------
// Projects  (8 realistic records)
// ---------------------------------------------------------------------------
export const MOCK_PROJECTS: Project[] = [
  { id: "p1", name: "AI DevFlow Intelligence Suite", description: "Full-stack developer workflow intelligence platform with AI insights.", status: "Active" as ProjectStatus, project_manager_id: "u2", progress: 62, start_date: "2026-01-01", end_date: "2026-12-31", created_at: "2026-01-01T08:00:00Z", updated_at: "2026-09-28T10:00:00Z", project_manager: { id: "u2", full_name: "Bob Martinez", email: "bob@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
  { id: "p2", name: "Mobile Companion App", description: "React Native companion app for DevFlow - iOS and Android.", status: "Planning" as ProjectStatus, project_manager_id: "u7", progress: 15, start_date: "2026-10-01", end_date: "2027-03-31", created_at: "2026-09-01T08:00:00Z", updated_at: "2026-09-25T10:00:00Z", project_manager: { id: "u7", full_name: "Grace Kim", email: "grace@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
  { id: "p3", name: "Legacy System Migration", description: "Migrate monolithic legacy system to a modern microservices architecture.", status: "On Hold" as ProjectStatus, project_manager_id: "u2", progress: 38, start_date: "2026-03-01", end_date: "2026-11-30", created_at: "2026-03-01T08:00:00Z", updated_at: "2026-09-10T10:00:00Z", project_manager: { id: "u2", full_name: "Bob Martinez", email: "bob@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
  { id: "p4", name: "CI/CD Pipeline Overhaul", description: "Redesign and automate the entire CI/CD pipeline for all services.", status: "Active" as ProjectStatus, project_manager_id: "u14", progress: 74, start_date: "2026-05-01", end_date: "2026-10-31", created_at: "2026-05-01T08:00:00Z", updated_at: "2026-09-28T08:00:00Z", project_manager: { id: "u14", full_name: "Nathan Brooks", email: "nathan@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
  { id: "p5", name: "Customer Portal v2", description: "Redesign the customer-facing portal with modern UX and real-time updates.", status: "Active" as ProjectStatus, project_manager_id: "u7", progress: 51, start_date: "2026-04-01", end_date: "2026-11-15", created_at: "2026-04-01T08:00:00Z", updated_at: "2026-09-27T14:00:00Z", project_manager: { id: "u7", full_name: "Grace Kim", email: "grace@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
  { id: "p6", name: "Security Audit 2026", description: "Comprehensive platform-wide security audit and vulnerability remediation.", status: "Completed" as ProjectStatus, project_manager_id: "u14", progress: 100, start_date: "2026-01-15", end_date: "2026-06-30", created_at: "2026-01-15T08:00:00Z", updated_at: "2026-06-30T17:00:00Z", project_manager: { id: "u14", full_name: "Nathan Brooks", email: "nathan@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
  { id: "p7", name: "Data Analytics Dashboard", description: "Internal analytics dashboard for product and business metrics.", status: "Planning" as ProjectStatus, project_manager_id: "u2", progress: 8, start_date: "2026-11-01", end_date: "2027-02-28", created_at: "2026-09-20T08:00:00Z", updated_at: "2026-09-28T09:00:00Z", project_manager: { id: "u2", full_name: "Bob Martinez", email: "bob@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
  { id: "p8", name: "API Gateway Integration", description: "Integrate third-party API gateway for rate limiting and authentication.", status: "Active" as ProjectStatus, project_manager_id: "u14", progress: 45, start_date: "2026-07-01", end_date: "2026-12-15", created_at: "2026-07-01T08:00:00Z", updated_at: "2026-09-26T10:00:00Z", project_manager: { id: "u14", full_name: "Nathan Brooks", email: "nathan@devflow.io", role: "MANAGER", is_active: true, created_at: "", updated_at: "" } },
];

// ---------------------------------------------------------------------------
// Tasks  (20 realistic records)
// ---------------------------------------------------------------------------
export const MOCK_TASKS: Task[] = [
  { id: "t1",  title: "Design database schema",            description: "Create ERD and define all tables for the platform.",           project_id: "p1", assigned_to: "u3",  status: "Completed"  as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-03-15", created_at: "2026-01-20T08:00:00Z", updated_at: "2026-03-15T17:00:00Z", project: { id: "p1", name: "AI DevFlow Intelligence Suite" }, assignee: { id: "u3",  full_name: "Carol Williams", email: "carol@devflow.io"  } },
  { id: "t2",  title: "Implement FastAPI routers",         description: "Build all REST API endpoints under /api/v1.",                  project_id: "p1", assigned_to: "u4",  status: "In Progress" as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-10-05", created_at: "2026-09-01T08:00:00Z", updated_at: "2026-09-28T10:00:00Z", project: { id: "p1", name: "AI DevFlow Intelligence Suite" }, assignee: { id: "u4",  full_name: "David Chen",     email: "david@devflow.io"  } },
  { id: "t3",  title: "Build Admin Dashboard",             description: "Create the admin panel with user and project management.",     project_id: "p1", assigned_to: "u3",  status: "In Progress" as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-10-20", created_at: "2026-09-10T08:00:00Z", updated_at: "2026-09-28T08:00:00Z", project: { id: "p1", name: "AI DevFlow Intelligence Suite" }, assignee: { id: "u3",  full_name: "Carol Williams", email: "carol@devflow.io"  } },
  { id: "t4",  title: "Write integration tests",           description: "Cover all API endpoints with pytest integration tests.",       project_id: "p1", assigned_to: "u6",  status: "To Do"       as TaskStatus, priority: "Medium"    as TaskPriority, due_date: "2026-10-25", created_at: "2026-09-15T08:00:00Z", updated_at: "2026-09-15T08:00:00Z", project: { id: "p1", name: "AI DevFlow Intelligence Suite" }, assignee: { id: "u6",  full_name: "Frank Nguyen",   email: "frank@devflow.io"  } },
  { id: "t5",  title: "Deploy to production",              description: "Set up CI/CD and deploy the application to production.",       project_id: "p1", assigned_to: "u16", status: "Blocked"     as TaskStatus, priority: "Critical"  as TaskPriority, due_date: "2026-11-01", created_at: "2026-09-20T08:00:00Z", updated_at: "2026-09-25T14:00:00Z", project: { id: "p1", name: "AI DevFlow Intelligence Suite" }, assignee: { id: "u16", full_name: "Paul Anderson",  email: "paul@devflow.io"   } },
  { id: "t6",  title: "Mobile UI wireframes",              description: "Create wireframes for all key screens in the mobile app.",     project_id: "p2", assigned_to: "u15", status: "In Progress" as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-10-15", created_at: "2026-09-05T08:00:00Z", updated_at: "2026-09-25T10:00:00Z", project: { id: "p2", name: "Mobile Companion App"           }, assignee: { id: "u15", full_name: "Olivia Torres",  email: "olivia@devflow.io" } },
  { id: "t7",  title: "Set up React Native project",       description: "Initialize RN project with navigation and state management.",  project_id: "p2", assigned_to: "u10", status: "To Do"       as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-10-20", created_at: "2026-09-10T08:00:00Z", updated_at: "2026-09-10T08:00:00Z", project: { id: "p2", name: "Mobile Companion App"           }, assignee: { id: "u10", full_name: "James OBrien",   email: "james@devflow.io"  } },
  { id: "t8",  title: "Audit legacy codebase",             description: "Document and audit all legacy services before migration.",     project_id: "p3", assigned_to: "u18", status: "Completed"   as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-05-30", created_at: "2026-03-05T08:00:00Z", updated_at: "2026-05-30T17:00:00Z", project: { id: "p3", name: "Legacy System Migration"       }, assignee: { id: "u18", full_name: "Rachel Scott",   email: "rachel@devflow.io" } },
  { id: "t9",  title: "Design microservices architecture", description: "Define service boundaries and communication patterns.",        project_id: "p3", assigned_to: "u4",  status: "Blocked"     as TaskStatus, priority: "Critical"  as TaskPriority, due_date: "2026-09-15", created_at: "2026-06-01T08:00:00Z", updated_at: "2026-09-12T10:00:00Z", project: { id: "p3", name: "Legacy System Migration"       }, assignee: { id: "u4",  full_name: "David Chen",     email: "david@devflow.io"  } },
  { id: "t10", title: "Set up GitHub Actions workflows",   description: "Configure CI workflows for build, test, and deploy.",         project_id: "p4", assigned_to: "u16", status: "Completed"   as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-07-15", created_at: "2026-05-10T08:00:00Z", updated_at: "2026-07-15T17:00:00Z", project: { id: "p4", name: "CI/CD Pipeline Overhaul"       }, assignee: { id: "u16", full_name: "Paul Anderson",  email: "paul@devflow.io"   } },
  { id: "t11", title: "Implement deployment pipeline",     description: "Set up staging and production deployment pipelines.",         project_id: "p4", assigned_to: "u6",  status: "In Progress" as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-10-10", created_at: "2026-08-01T08:00:00Z", updated_at: "2026-09-20T10:00:00Z", project: { id: "p4", name: "CI/CD Pipeline Overhaul"       }, assignee: { id: "u6",  full_name: "Frank Nguyen",   email: "frank@devflow.io"  } },
  { id: "t12", title: "UX research and interviews",        description: "Conduct user interviews for the new portal design.",          project_id: "p5", assigned_to: "u15", status: "Completed"   as TaskStatus, priority: "Medium"    as TaskPriority, due_date: "2026-06-30", created_at: "2026-04-10T08:00:00Z", updated_at: "2026-06-30T17:00:00Z", project: { id: "p5", name: "Customer Portal v2"            }, assignee: { id: "u15", full_name: "Olivia Torres",  email: "olivia@devflow.io" } },
  { id: "t13", title: "Implement real-time notifications", description: "Add WebSocket-based real-time notification system.",          project_id: "p5", assigned_to: "u10", status: "In Progress" as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-10-15", created_at: "2026-08-15T08:00:00Z", updated_at: "2026-09-25T10:00:00Z", project: { id: "p5", name: "Customer Portal v2"            }, assignee: { id: "u10", full_name: "James OBrien",   email: "james@devflow.io"  } },
  { id: "t14", title: "Penetration testing",               description: "Conduct full penetration testing of all API endpoints.",      project_id: "p6", assigned_to: "u18", status: "Completed"   as TaskStatus, priority: "Critical"  as TaskPriority, due_date: "2026-05-31", created_at: "2026-02-01T08:00:00Z", updated_at: "2026-05-31T17:00:00Z", project: { id: "p6", name: "Security Audit 2026"           }, assignee: { id: "u18", full_name: "Rachel Scott",   email: "rachel@devflow.io" } },
  { id: "t15", title: "Vulnerability remediation",         description: "Fix all critical and high vulnerabilities found in the audit.", project_id: "p6", assigned_to: "u4",  status: "Completed"   as TaskStatus, priority: "Critical"  as TaskPriority, due_date: "2026-06-28", created_at: "2026-06-01T08:00:00Z", updated_at: "2026-06-30T17:00:00Z", project: { id: "p6", name: "Security Audit 2026"           }, assignee: { id: "u4",  full_name: "David Chen",     email: "david@devflow.io"  } },
  { id: "t16", title: "Define analytics KPIs",             description: "Work with product team to define key performance indicators.", project_id: "p7", assigned_to: "u3",  status: "To Do"       as TaskStatus, priority: "Medium"    as TaskPriority, due_date: "2026-11-15", created_at: "2026-09-22T08:00:00Z", updated_at: "2026-09-22T08:00:00Z", project: { id: "p7", name: "Data Analytics Dashboard"     }, assignee: { id: "u3",  full_name: "Carol Williams", email: "carol@devflow.io"  } },
  { id: "t17", title: "Evaluate gateway providers",        description: "Compare Kong, AWS API Gateway, and Nginx Plus.",             project_id: "p8", assigned_to: "u6",  status: "Completed"   as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-08-15", created_at: "2026-07-05T08:00:00Z", updated_at: "2026-08-15T17:00:00Z", project: { id: "p8", name: "API Gateway Integration"      }, assignee: { id: "u6",  full_name: "Frank Nguyen",   email: "frank@devflow.io"  } },
  { id: "t18", title: "Implement rate limiting",           description: "Configure rate limiting rules per API key and endpoint.",    project_id: "p8", assigned_to: "u16", status: "In Progress" as TaskStatus, priority: "High"     as TaskPriority, due_date: "2026-10-30", created_at: "2026-09-01T08:00:00Z", updated_at: "2026-09-25T12:00:00Z", project: { id: "p8", name: "API Gateway Integration"      }, assignee: { id: "u16", full_name: "Paul Anderson",  email: "paul@devflow.io"   } },
  { id: "t19", title: "Set up monitoring dashboards",      description: "Configure Grafana dashboards for all services.",             project_id: "p4", assigned_to: "u10", status: "To Do"       as TaskStatus, priority: "Medium"    as TaskPriority, due_date: "2026-10-25", created_at: "2026-09-15T08:00:00Z", updated_at: "2026-09-15T08:00:00Z", project: { id: "p4", name: "CI/CD Pipeline Overhaul"       }, assignee: { id: "u10", full_name: "James OBrien",   email: "james@devflow.io"  } },
  { id: "t20", title: "Performance load testing",          description: "Run k6 load tests against all critical endpoints.",          project_id: "p1", assigned_to: "u18", status: "To Do"       as TaskStatus, priority: "Medium"    as TaskPriority, due_date: "2026-11-10", created_at: "2026-09-25T08:00:00Z", updated_at: "2026-09-25T08:00:00Z", project: { id: "p1", name: "AI DevFlow Intelligence Suite" }, assignee: { id: "u18", full_name: "Rachel Scott",   email: "rachel@devflow.io" } },
];

// ---------------------------------------------------------------------------
// Activity Logs  (20 realistic records)
// ---------------------------------------------------------------------------
export const MOCK_ACTIVITY: ActivityLog[] = [
  { id: "a1",  user_id: "u1",  action: "created",     entity_type: "Project",    entity_id: "p1",    description: "Alice Johnson created project 'AI DevFlow Intelligence Suite'",             created_at: "2026-09-28T10:00:00Z", user: { id: "u1",  full_name: "Alice Johnson",  email: "alice@devflow.io"  } },
  { id: "a2",  user_id: "u4",  action: "completed",   entity_type: "Task",       entity_id: "t1",    description: "David Chen completed task 'Design database schema'",                       created_at: "2026-09-28T09:30:00Z", user: { id: "u4",  full_name: "David Chen",     email: "david@devflow.io"  } },
  { id: "a3",  user_id: "u2",  action: "assigned",    entity_type: "Task",       entity_id: "t3",    description: "Bob Martinez assigned 'Build Admin Dashboard' to Carol Williams",          created_at: "2026-09-28T08:45:00Z", user: { id: "u2",  full_name: "Bob Martinez",   email: "bob@devflow.io"    } },
  { id: "a4",  user_id: "u3",  action: "updated",     entity_type: "Task",       entity_id: "t2",    description: "Carol Williams updated task 'Implement FastAPI routers' to In Progress",   created_at: "2026-09-27T17:00:00Z", user: { id: "u3",  full_name: "Carol Williams", email: "carol@devflow.io"  } },
  { id: "a5",  user_id: "u1",  action: "activated",   entity_type: "User",       entity_id: "u13",   description: "Alice Johnson activated user Mia Robinson",                                created_at: "2026-09-27T15:30:00Z", user: { id: "u1",  full_name: "Alice Johnson",  email: "alice@devflow.io"  } },
  { id: "a6",  user_id: "u6",  action: "created",     entity_type: "Task",       entity_id: "t11",   description: "Frank Nguyen created task 'Implement deployment pipeline'",               created_at: "2026-09-27T14:00:00Z", user: { id: "u6",  full_name: "Frank Nguyen",   email: "frank@devflow.io"  } },
  { id: "a7",  user_id: "u7",  action: "created",     entity_type: "Project",    entity_id: "p2",    description: "Grace Kim created project 'Mobile Companion App'",                        created_at: "2026-09-27T12:00:00Z", user: { id: "u7",  full_name: "Grace Kim",      email: "grace@devflow.io"  } },
  { id: "a8",  user_id: "u16", action: "blocked",     entity_type: "Task",       entity_id: "t5",    description: "Paul Anderson flagged task 'Deploy to production' as Blocked",            created_at: "2026-09-27T11:00:00Z", user: { id: "u16", full_name: "Paul Anderson",  email: "paul@devflow.io"   } },
  { id: "a9",  user_id: "u1",  action: "created",     entity_type: "Risk",       entity_id: "r1",    description: "Alice Johnson flagged a Critical risk on AI DevFlow project",             created_at: "2026-09-27T09:30:00Z", user: { id: "u1",  full_name: "Alice Johnson",  email: "alice@devflow.io"  } },
  { id: "a10", user_id: "u14", action: "updated",     entity_type: "Project",    entity_id: "p4",    description: "Nathan Brooks updated CI/CD Pipeline Overhaul progress to 74%",           created_at: "2026-09-26T16:00:00Z", user: { id: "u14", full_name: "Nathan Brooks",  email: "nathan@devflow.io" } },
  { id: "a11", user_id: "u18", action: "completed",   entity_type: "Task",       entity_id: "t8",    description: "Rachel Scott completed 'Audit legacy codebase'",                         created_at: "2026-09-26T14:30:00Z", user: { id: "u18", full_name: "Rachel Scott",   email: "rachel@devflow.io" } },
  { id: "a12", user_id: "u10", action: "created",     entity_type: "Task",       entity_id: "t13",   description: "James OBrien created task 'Implement real-time notifications'",          created_at: "2026-09-26T13:00:00Z", user: { id: "u10", full_name: "James OBrien",   email: "james@devflow.io"  } },
  { id: "a13", user_id: "u1",  action: "deactivated", entity_type: "User",       entity_id: "u12",   description: "Alice Johnson deactivated user Leo Ramirez",                              created_at: "2026-09-26T11:00:00Z", user: { id: "u1",  full_name: "Alice Johnson",  email: "alice@devflow.io"  } },
  { id: "a14", user_id: "u2",  action: "created",     entity_type: "Repository", entity_id: "repo1", description: "Bob Martinez connected repository 'ai-devflow-backend'",                  created_at: "2026-09-25T15:00:00Z", user: { id: "u2",  full_name: "Bob Martinez",   email: "bob@devflow.io"    } },
  { id: "a15", user_id: "u3",  action: "resolved",    entity_type: "Risk",       entity_id: "r4",    description: "Carol Williams resolved dependency vulnerability risk",                   created_at: "2026-09-25T13:00:00Z", user: { id: "u3",  full_name: "Carol Williams", email: "carol@devflow.io"  } },
  { id: "a16", user_id: "u4",  action: "updated",     entity_type: "Task",       entity_id: "t9",    description: "David Chen updated 'Design microservices architecture' to Blocked",       created_at: "2026-09-25T11:00:00Z", user: { id: "u4",  full_name: "David Chen",     email: "david@devflow.io"  } },
  { id: "a17", user_id: "u15", action: "completed",   entity_type: "Task",       entity_id: "t12",   description: "Olivia Torres completed 'UX research and interviews'",                   created_at: "2026-09-24T17:00:00Z", user: { id: "u15", full_name: "Olivia Torres",  email: "olivia@devflow.io" } },
  { id: "a18", user_id: "u1",  action: "updated",     entity_type: "Settings",   entity_id: null,    description: "Alice Johnson updated platform notification settings",                     created_at: "2026-09-24T14:00:00Z", user: { id: "u1",  full_name: "Alice Johnson",  email: "alice@devflow.io"  } },
  { id: "a19", user_id: "u7",  action: "assigned",    entity_type: "Task",       entity_id: "t6",    description: "Grace Kim assigned 'Mobile UI wireframes' to Olivia Torres",              created_at: "2026-09-24T12:00:00Z", user: { id: "u7",  full_name: "Grace Kim",      email: "grace@devflow.io"  } },
  { id: "a20", user_id: "u14", action: "created",     entity_type: "Project",    entity_id: "p7",    description: "Nathan Brooks created project 'Data Analytics Dashboard'",               created_at: "2026-09-23T10:00:00Z", user: { id: "u14", full_name: "Nathan Brooks",  email: "nathan@devflow.io" } },
];

// ---------------------------------------------------------------------------
// Workflow Risks  (10 realistic records)
// ---------------------------------------------------------------------------
export const MOCK_RISKS: WorkflowRisk[] = [
  { id: "r1",  project_id: "p1", task_id: "t5",  risk_type: "Deployment Failure",       severity: "Critical" as RiskSeverity, description: "CI/CD pipeline failing for 3 consecutive runs. Production release at risk.",   status: "Open" as RiskStatus,       created_at: "2026-09-27T09:30:00Z", updated_at: "2026-09-28T10:00:00Z" },
  { id: "r2",  project_id: "p1", task_id: null,  risk_type: "Sprint Overrun",            severity: "High"     as RiskSeverity, description: "5 tasks in the current sprint are past their due dates with no updates.",    status: "Open" as RiskStatus,       created_at: "2026-09-26T14:00:00Z", updated_at: "2026-09-27T10:00:00Z" },
  { id: "r3",  project_id: "p1", task_id: null,  risk_type: "Low Test Coverage",         severity: "Medium"   as RiskSeverity, description: "Test coverage at 34%. Recommended minimum is 80% before production.",       status: "Monitoring" as RiskStatus, created_at: "2026-09-25T11:00:00Z", updated_at: "2026-09-26T10:00:00Z" },
  { id: "r4",  project_id: "p2", task_id: null,  risk_type: "Dependency Vulnerability",  severity: "High"     as RiskSeverity, description: "High-severity CVE in react-native dependency. Update required.",            status: "Resolved" as RiskStatus,   created_at: "2026-09-24T09:00:00Z", updated_at: "2026-09-25T13:00:00Z" },
  { id: "r5",  project_id: "p3", task_id: "t9",  risk_type: "Blocked Milestone",         severity: "Critical" as RiskSeverity, description: "Architecture design task blocked for 2 weeks. Migration milestone at risk.", status: "Open" as RiskStatus,       created_at: "2026-09-20T10:00:00Z", updated_at: "2026-09-28T09:00:00Z" },
  { id: "r6",  project_id: "p4", task_id: null,  risk_type: "Resource Shortage",         severity: "Medium"   as RiskSeverity, description: "Lead DevOps engineer on leave. Pipeline overhaul may miss deadline.",       status: "Monitoring" as RiskStatus, created_at: "2026-09-22T08:00:00Z", updated_at: "2026-09-25T10:00:00Z" },
  { id: "r7",  project_id: "p5", task_id: null,  risk_type: "Scope Creep",               severity: "Medium"   as RiskSeverity, description: "Customer requirements expanded by 30% beyond original scope estimates.",    status: "Monitoring" as RiskStatus, created_at: "2026-09-18T11:00:00Z", updated_at: "2026-09-22T10:00:00Z" },
  { id: "r8",  project_id: "p8", task_id: null,  risk_type: "Vendor Lock-in",            severity: "Low"      as RiskSeverity, description: "Architecture heavily dependent on a single cloud provider for gateway.",    status: "Open" as RiskStatus,       created_at: "2026-09-15T09:00:00Z", updated_at: "2026-09-20T10:00:00Z" },
  { id: "r9",  project_id: "p1", task_id: null,  risk_type: "Technical Debt",            severity: "Low"      as RiskSeverity, description: "Accumulated technical debt in the auth module needs refactoring.",          status: "Monitoring" as RiskStatus, created_at: "2026-09-10T10:00:00Z", updated_at: "2026-09-20T09:00:00Z" },
  { id: "r10", project_id: "p6", task_id: null,  risk_type: "Compliance Gap",            severity: "High"     as RiskSeverity, description: "Missing GDPR-compliant data deletion flow. Legal review required.",        status: "Resolved" as RiskStatus,   created_at: "2026-06-01T10:00:00Z", updated_at: "2026-06-25T17:00:00Z" },
];

// ---------------------------------------------------------------------------
// Repositories  (8 realistic records)
// ---------------------------------------------------------------------------
export const MOCK_REPOSITORIES: Repository[] = [
  { id: "repo1", project_id: "p1", repository_name: "ai-devflow-backend",   repository_url: "https://github.com/devflow-org/ai-devflow-backend",    provider: "GitHub",    status: "Active",       connected_at: "2026-01-10T10:00:00Z" },
  { id: "repo2", project_id: "p1", repository_name: "ai-devflow-frontend",  repository_url: "https://github.com/devflow-org/ai-devflow-frontend",   provider: "GitHub",    status: "Active",       connected_at: "2026-01-10T10:30:00Z" },
  { id: "repo3", project_id: "p2", repository_name: "mobile-companion",     repository_url: "https://github.com/devflow-org/mobile-companion",      provider: "GitHub",    status: "Active",       connected_at: "2026-09-01T09:00:00Z" },
  { id: "repo4", project_id: "p3", repository_name: "legacy-monolith",      repository_url: "https://gitlab.com/devflow-org/legacy-monolith",       provider: "GitLab",    status: "Active",       connected_at: "2026-03-01T10:00:00Z" },
  { id: "repo5", project_id: "p4", repository_name: "devops-pipelines",     repository_url: "https://github.com/devflow-org/devops-pipelines",      provider: "GitHub",    status: "Active",       connected_at: "2026-05-01T11:00:00Z" },
  { id: "repo6", project_id: "p5", repository_name: "customer-portal-v2",   repository_url: "https://github.com/devflow-org/customer-portal-v2",    provider: "GitHub",    status: "Active",       connected_at: "2026-04-01T09:00:00Z" },
  { id: "repo7", project_id: "p8", repository_name: "api-gateway-config",   repository_url: "https://bitbucket.org/devflow-org/api-gateway-config", provider: "Bitbucket", status: "Active",       connected_at: "2026-07-01T10:00:00Z" },
  { id: "repo8", project_id: "p6", repository_name: "security-tools",       repository_url: "https://github.com/devflow-org/security-tools",        provider: "GitHub",    status: "Disconnected", connected_at: "2026-01-15T08:00:00Z" },
];

// ---------------------------------------------------------------------------
// Dashboard stats (derived from mock data above)
// ---------------------------------------------------------------------------
export function getMockDashboardStats() {
  return {
    totalUsers:     MOCK_USERS.length,
    activeProjects: MOCK_PROJECTS.filter((p) => p.status === "Active").length,
    openTasks:      MOCK_TASKS.filter((t) => t.status !== "Completed").length,
    openRisks:      MOCK_RISKS.filter((r) => r.status === "Open").length,
    connectedRepos: MOCK_REPOSITORIES.filter((r) => r.status === "Active").length,
  };
}
